name: Published NPM Package 

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # 选择Node.js环境
        with:
          node-version: '22'  # 配置Node.js版本
          registry-url: 'https://registry-npmjs.org/'

      - name: Clean npm cache
        run: npm cache clean --force 

      - name: Install dependencies
        run: npm install 

      - name: Install rollup and tslib
        run: npm install -D rollup tslib
      
      - name: Build project
        run: npm run build

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
